/* The exercises of the other sports: their themes (with the words that find them in a text) and a base of classic exercises
   that fills « Exercices du club » from the first day. Each line: [theme, title, minutes, organisation, consignes, matériel, formats, size].
   Football keeps its own list (exos.js). */
const SPORT_EXOS = {
  basket: {
    themes: [['echauffement', '🔥 Échauffement'], ['dribble', '🏀 Dribble'], ['passe', '🤝 Passe'], ['tir', '🎯 Tir'], ['un', '⚔️ 1 contre 1'], ['defense', '🛡️ Défense'],
      ['rebond', '🙌 Rebond'], ['transitions', '⚡ Contre-attaque'], ['attaque', '🧠 Attaque placée'], ['physique', '🏃 Physique'], ['jeu', '🏟️ Jeu / match à thème'], ['calme', '🧘 Retour au calme']],
    keys: { echauffement: /échauff|activation|mobilit/i, dribble: /dribbl|main faible|changement de main|cross/i, passe: /passe|réception/i, tir: /tir|shoot|lancer|double pas|lay/i,
      un: /1 ?c(ontre)? ?1|duel|un contre un/i, defense: /défen|aide|rotation défensive|homme à homme|zone/i, rebond: /rebond|box ?out|écran retard/i,
      transitions: /contre-attaque|transition|course|repli/i, attaque: /attaque placée|pick|écran|jeu à 2|système/i, physique: /physi|vitesse|sprint|appuis|gainage/i,
      jeu: /match|3 ?c(ontre)? ?3|5 ?c(ontre)? ?5|jeu réduit/i, calme: /retour au calme|étirement/i },
    base: [
      ['echauffement', 'Gammes de dribble en ligne', 10, 'Une ligne par panier, aller-retour sur la longueur : dribble main droite, main gauche, changement de main devant, entre les jambes.', 'Regarder devant soi\nBallon à hauteur de hanche\nMain faible autant que main forte', 'Un ballon par joueur', '', ''],
      ['echauffement', 'Passes à 3 en mouvement', 10, 'Trois colonnes, on monte sur la longueur en se passant le ballon sans dribbler, on finit par un double pas.', 'Passe devant le partenaire\nCourir dans son couloir\nFinir sans marcher', 'Ballons', '', ''],
      ['dribble', 'Slalom de plots et changements de main', 12, '6 plots en zigzag : à chaque plot, un changement de main (devant, dans le dos, entre les jambes), puis tir.', 'Changer de rythme au plot\nProtéger le ballon avec le corps', 'Plots, ballons', '', ''],
      ['passe', 'Passe et va au triangle', 10, 'Trois joueurs en triangle de 5 m : je passe et je prends la place de celui qui a reçu.', 'Passe à deux mains poitrine puis à terre\nAppeler le ballon, mains prêtes', 'Ballons, plots', '', '6x6'],
      ['tir', 'Double pas des deux côtés', 12, 'Deux colonnes à 45° : un passeur, un tireur qui finit en double pas, côté droit puis gauche.', 'Bon pied d\'appel\nMonter la balle haut\nViser le carré de la planche', 'Ballons', '', ''],
      ['tir', 'Tirs en 5 positions', 15, '5 spots autour de la raquette (0°, 45°, 90°) : 5 tirs par spot, un rebondeur passe.', 'Pieds orientés vers le panier\nCoude sous le ballon\nFinir le geste, poignet cassé', 'Ballons', '', ''],
      ['un', '1 contre 1 depuis l\'aile', 12, 'L\'attaquant reçoit à l\'aile, le défenseur vient de la raquette : 1 contre 1 jusqu\'au panier ou à la perte.', 'Attaquer le pied avant du défenseur\nFeinte avant de partir\nDéfenseur : rester entre l\'attaquant et le panier', 'Ballons', '', ''],
      ['defense', 'Glissés défensifs en zigzag', 8, 'Sur la largeur, l\'attaquant dribble en zigzag, le défenseur glisse sans croiser les pieds, mains actives.', 'Fléchi, poids sur l\'avant des pieds\nNe pas croiser les jambes', 'Ballons', '', ''],
      ['rebond', 'Box-out à 2 contre 2', 10, 'Le coach tire, chaque défenseur bloque son attaquant puis va chercher le rebond.', 'Contact d\'abord, ballon ensuite\nFesses vers l\'attaquant, bras écartés', 'Ballons', '', ''],
      ['transitions', 'Contre-attaque 3 contre 2 puis 2 contre 1', 15, 'Trois attaquants contre deux défenseurs, puis les deux défenseurs repartent à 2 contre 1 vers l\'autre panier.', 'Écarter dans les couloirs\nLe porteur au centre fixe\nPasse avant le dernier défenseur', 'Ballons', 'b5', ''],
      ['attaque', 'Jeu à 2 : pick and roll', 15, 'Le meneur à 45°, le pivot vient poser l\'écran : 2 contre 2 sur la lecture (tir, pénétration, passe au roll).', 'Bien poser l\'écran, immobile\nUtiliser l\'écran épaule contre épaule\nLe pivot roule vers le panier', 'Ballons', '', ''],
      ['jeu', '3 contre 3 demi-terrain', 15, 'Matchs de 3 minutes sur un panier : panier = on garde le ballon, après un rebond défensif on ressort derrière la ligne à 3 points.', 'Bouger sans ballon\nCommuniquer en défense', 'Chasubles, ballons', '', ''],
      ['physique', 'Suicides avec ballon', 8, 'Aller-retour aux lignes successives (lancer franc, milieu, lancer franc opposé, fond) en dribblant.', 'Tenir le rythme\nToucher les lignes', 'Ballons', '', ''],
      ['calme', 'Lancers francs et étirements', 8, 'Par deux : 10 lancers francs chacun en récupérant, puis étirements des jambes.', 'Routine avant chaque lancer\nRespirer', 'Ballons', '', ''],
    ],
  },
  hand: {
    themes: [['echauffement', '🔥 Échauffement'], ['technique', '🤝 Passe et réception'], ['tir', '🎯 Tir'], ['un', '⚔️ Duel 1 contre 1'], ['defense', '🛡️ Défense'],
      ['gardien', '🧤 Gardien de but'], ['transitions', '⚡ Montée de balle'], ['attaque', '🧠 Attaque placée'], ['physique', '🏃 Physique'], ['jeu', '🏟️ Jeu / match à thème'], ['calme', '🧘 Retour au calme']],
    keys: { echauffement: /échauff|activation|mobilit/i, technique: /passe|réception|manipulation|dribble/i, tir: /tir|appui|suspension|lob|rucher/i, un: /1 ?c(ontre)? ?1|duel|fixation|débordement/i,
      defense: /défen|0-6|1-5|3-2-1|dissuasion|interception/i, gardien: /gardien|parade|arrêt/i, transitions: /montée de balle|contre-attaque|repli|transition/i,
      attaque: /attaque placée|croisé|pivot|enclenchement|bloc/i, physique: /physi|vitesse|sprint|appuis|gainage/i, jeu: /match|jeu réduit|4 ?c(ontre)? ?4/i, calme: /retour au calme|étirement/i },
    base: [
      ['echauffement', 'Passes en mouvement par 2', 10, 'Par deux sur la longueur, on se passe le ballon en courant, sans marcher (3 pas maximum).', 'Recevoir en mouvement\nPasse à hauteur de poitrine\nRespecter les 3 pas', 'Ballons', '', ''],
      ['technique', 'Passe et suis en carré', 10, 'Quatre plots en carré de 8 m, une colonne par plot : je passe au plot suivant et je suis ma passe.', 'Passe à une main, bras armé haut\nAppeler, mains en coupe', 'Plots, ballons', '', '8x8'],
      ['tir', 'Tirs en appui depuis les 9 m', 12, 'Une colonne à 9 m face au but, le gardien en place : tir en appui en visant les coins.', 'Bras armé haut\nPied opposé au bras devant\nRegarder le gardien avant de tirer', 'Ballons, plots', '', ''],
      ['tir', 'Tir en suspension après 3 pas', 12, 'Départ à 12 m : réception, 3 pas, impulsion et tir en suspension au-dessus d\'un obstacle bas.', 'Impulsion du pied opposé\nTirer au plus haut', 'Ballons, obstacle bas', '', ''],
      ['un', 'Duel 1 contre 1 en couloir', 12, 'Couloir de 5 m de large jusqu\'à la zone : l\'attaquant doit déborder le défenseur et tirer.', 'Feinte de corps avant d\'accélérer\nDéfenseur : bras actifs, rester devant', 'Ballons, plots', '', '10x5'],
      ['defense', 'Défense 0-6 : glisser ensemble', 15, 'Six défenseurs sur la zone contre 6 attaquants qui font circuler le ballon : la défense glisse et sort sur le porteur.', 'Sortir sur le porteur, puis revenir\nSe parler\nBras levés', 'Ballons, chasubles', 'h7', ''],
      ['gardien', 'Gardien : tirs en série', 10, 'Le gardien en place, 6 tireurs à 7 m tirent l\'un après l\'autre (haut, bas, côtés).', 'Rester grand, bras ouverts\nSe replacer vite après chaque tir', 'Ballons', '', ''],
      ['transitions', 'Montée de balle à 3 contre 2', 15, 'Après l\'arrêt, le gardien relance vite : 3 attaquants contre 2 défenseurs qui se replient.', 'Relance rapide et longue\nÉcarter le jeu\nFinir avant le repli', 'Ballons, chasubles', '', ''],
      ['attaque', 'Croisé arrière - demi-centre', 15, 'L\'arrière part vers le centre, le demi-centre croise derrière lui : 2 contre 2 puis 3 contre 3 avec le pivot.', 'Fixer avant de passer\nCroiser dans le dos du porteur', 'Ballons', '', ''],
      ['jeu', 'Match à 4 contre 4 sur demi-terrain', 15, 'Demi-terrain avec un but : après la récupération, ressortir au-delà de la ligne des 9 m avant d\'attaquer.', 'Occuper la largeur\nDéfense agressive sur le porteur', 'Chasubles, ballons', '', ''],
      ['physique', 'Circuit appuis et gainage', 12, 'Ateliers de 30 s : échelle de rythme, sauts latéraux, gainage, sprint 10 m.', 'Qualité des appuis\nRécupérer entre les ateliers', 'Échelle, plots', '', ''],
      ['calme', 'Jonglages et étirements', 8, 'Manipulation du ballon en marchant (autour de la taille, entre les jambes), puis étirements.', 'Respirer\nÉtirer sans à-coups', 'Ballons', '', ''],
    ],
  },
  rugby: {
    themes: [['echauffement', '🔥 Échauffement'], ['passe', '🤝 Passe et réception'], ['pied', '🦶 Jeu au pied'], ['plaquage', '🛡️ Plaquage et défense'], ['contact', '💥 Contact et ruck'],
      ['conquete', '🏉 Conquête (mêlée, touche)'], ['soutien', '🔄 Soutien et continuité'], ['attaque', '⚡ Attaque et décalage'], ['physique', '🏃 Physique'], ['jeu', '🏟️ Jeu / match à thème'], ['calme', '🧘 Retour au calme']],
    keys: { echauffement: /échauff|activation|mobilit/i, passe: /passe|réception|vrille|sautée/i, pied: /jeu au pied|coup de pied|chandelle|rasant|drop|pénalité/i,
      plaquage: /plaqu|défen|montée|rideau/i, contact: /contact|ruck|maul|grattage|percussion/i, conquete: /mêlée|touche|alignement|lancer/i, soutien: /soutien|continuité|offload|libération/i,
      attaque: /décalage|surnombre|2 ?c(ontre)? ?1|attaque|ligne d'avantage/i, physique: /physi|vitesse|sprint|appuis|gainage|puissance/i, jeu: /match|jeu réduit|toucher|flag/i, calme: /retour au calme|étirement/i },
    base: [
      ['echauffement', 'Passes en ligne de 4', 10, 'Quatre joueurs en ligne décalée, on avance et le ballon va d\'un bout à l\'autre puis revient.', 'Passer vers l\'arrière\nMains tendues vers le passeur\nCourir droit', 'Ballons, plots', '', '40x20'],
      ['passe', 'Passes sautées et vrillées', 12, 'Par 4 sur la largeur : passe simple, puis passe qui saute un joueur, puis passe vrillée sur 15 m.', 'Pousser avec la main arrière\nViser devant le receveur', 'Ballons', '', ''],
      ['attaque', '2 contre 1 en couloir', 12, 'Couloir de 10 m : deux attaquants contre un défenseur, fixer puis passer au bon moment.', 'Attaquer l\'épaule intérieure du défenseur\nPasser quand il s\'engage', 'Ballons, plots', '', '20x10'],
      ['attaque', '3 contre 2 puis 4 contre 3', 15, 'Sur 30 m, le surnombre progresse : 3 contre 2, puis un défenseur et un attaquant entrent.', 'Fixer son vis-à-vis\nGarder la largeur', 'Ballons, chasubles', '', ''],
      ['plaquage', 'Plaquage sur boucliers', 12, 'Par 2 : l\'un tient le bouclier en marchant, l\'autre plaque épaule dans le bouclier puis se relève.', 'Tête sur le côté, jamais devant\nEnserrer et serrer les bras\nSe relever vite', 'Boucliers', '', ''],
      ['plaquage', 'Montée défensive en rideau', 12, 'Ligne de 4 défenseurs face à 5 attaquants : monter ensemble et glisser vers l\'extérieur.', 'Monter ensemble\nSe parler\nPlaquer bas', 'Chasubles, ballons', '', ''],
      ['contact', 'Ruck : libération et grattage', 12, 'Un porteur va au sol, son soutien protège le ballon, un adversaire tente de le gratter.', 'Arriver bas, pieds en appui\nLibérer le ballon vite', 'Ballons, boucliers', '', ''],
      ['conquete', 'Touche : lancer et saut', 15, 'Alignement de 3 (sauteur et deux lifteurs) et un lanceur à 5 m : appels, lancers et réceptions.', 'Lancer droit et tendu\nLifteurs synchronisés', 'Ballons', '', ''],
      ['soutien', 'Jeu au toucher à 2 secondes', 15, 'Match au toucher : le porteur touché a 2 secondes pour passer, le soutien doit être là.', 'Soutien proche, derrière le porteur\nDonner une solution à gauche et à droite', 'Ballons, chasubles', '', '40x25'],
      ['pied', 'Jeu au pied de déplacement', 12, 'Par 2 à 20 m : coups de pied rasants puis chandelles, le partenaire réceptionne.', 'Regarder le ballon jusqu\'au pied\nRéception bras en panier', 'Ballons', '', ''],
      ['physique', 'Circuit vitesse et appuis', 12, 'Ateliers de 20 s : échelle, crochets entre plots, sprint 15 m, relevés du sol.', 'Appuis courts et rapides\nRécupérer entre les ateliers', 'Échelle, plots', '', ''],
      ['calme', 'Passes en marchant et étirements', 8, 'Passes à deux en marchant, puis étirements des jambes et du dos.', 'Respirer\nÉtirer sans à-coups', 'Ballons', '', ''],
    ],
  },
  volley: {
    themes: [['echauffement', '🔥 Échauffement'], ['technique', '🤲 Touche et manchette'], ['service', '🎯 Service'], ['reception', '🛡️ Réception'], ['attaque', '💥 Attaque'],
      ['contre', '🧱 Contre'], ['defense', '🤸 Défense'], ['physique', '🏃 Physique'], ['jeu', '🏟️ Jeu / match à thème'], ['calme', '🧘 Retour au calme']],
    keys: { echauffement: /échauff|activation|mobilit/i, technique: /touche|manchette|passe/i, service: /service|smash de service|flottant/i, reception: /réception|recevoir/i,
      attaque: /attaque|smash|frappe|élan/i, contre: /contre|bloc/i, defense: /défen|plonge|récupér/i, physique: /physi|détente|vitesse|appuis|gainage/i, jeu: /match|jeu réduit|2 ?c(ontre)? ?2|4 ?c(ontre)? ?4|6 ?c(ontre)? ?6/i, calme: /retour au calme|étirement/i },
    base: [
      ['echauffement', 'Échanges à 2 en touche', 10, 'Par 2 de part et d\'autre du filet (ou face à face à 4 m) : échanges en touche haute.', 'Mains en coupe au-dessus du front\nPousser avec les jambes', 'Ballons', '', ''],
      ['technique', 'Manchette contre le mur', 8, 'Chacun face au mur : manchettes continues à 2 m de hauteur.', 'Bras tendus, plan de frappe stable\nSe placer sous le ballon avec les jambes', 'Ballons, mur', '', ''],
      ['technique', 'Touche - manchette en triangle', 12, 'Trois joueurs en triangle : touche vers l\'un, manchette vers l\'autre, en tournant.', 'Orienter les épaules vers la cible\nAnnoncer « j\'ai »', 'Ballons', '', ''],
      ['service', 'Service en zones', 12, 'Le terrain adverse est découpé en 6 zones : chacun sert 3 ballons par zone annoncée.', 'Lancer régulier\nBras qui frappe haut et vers l\'avant', 'Ballons, plots', '', ''],
      ['reception', 'Réception à 3 sur service', 15, 'Trois réceptionneurs, un passeur à la cible : le coach ou un serveur sert, on vise le passeur.', 'Être arrêté avant le contact\nSe parler entre réceptionneurs', 'Ballons, cible', '', ''],
      ['attaque', 'Attaque en zone 4 après passe', 15, 'Le passeur en zone 2-3 passe haut en 4, les attaquants prennent leur élan et frappent.', 'Élan en 3 temps, bras en arrière\nFrapper au point le plus haut', 'Ballons', '', ''],
      ['contre', 'Contre à deux', 12, 'Deux contreurs se déplacent ensemble face à un attaquant sur plinth ou qui frappe en 4.', 'Pas chassés, pas croisés\nMains au-dessus du filet, pénétrer', 'Ballons, plinth', '', ''],
      ['defense', 'Défense sur attaque du coach', 12, 'Le coach attaque depuis l\'autre côté, trois défenseurs remontent le ballon vers la cible.', 'Position basse, bras devant\nTout ballon est jouable', 'Ballons', '', ''],
      ['jeu', 'Match à 4 contre 4 avec 3 touches obligatoires', 15, 'Terrain réduit, chaque équipe doit faire 3 touches avant de renvoyer.', 'Construire réception - passe - attaque\nCommuniquer', 'Ballons', '', ''],
      ['physique', 'Détente et appuis', 10, 'Ateliers : sauts sur place bras en haut, pas chassés, sprint 6 m et retour.', 'Atterrir sur les deux pieds\nQualité avant quantité', 'Plots', '', ''],
      ['calme', 'Jonglages et étirements', 8, 'Jonglages libres en touche et manchette, puis étirements épaules et jambes.', 'Respirer\nÉtirer sans à-coups', 'Ballons', '', ''],
    ],
  },
};
