/* More exercises and sessions for basket, handball, rugby and volley (1.21), so that these sports have as much as football.
   Written for the app (no copy). Same shapes as sport-exos.js (base: [theme, title, minutes, organisation, consignes « \n », matériel, formats, size])
   and sessions-sports.js ({ sys, fmt, title, goal, ex: [[theme, title, minutes, organisation, consignes « | », matériel, size]] }). */
(() => {
  const X = typeof SPORT_EXOS !== 'undefined' ? SPORT_EXOS : null, SS = typeof SESSIONS_SPORTS !== 'undefined' ? SESSIONS_SPORTS : null;
  const EX = {
    basket: [
      ['echauffement', 'Jeu des 10 passes', 8, 'Deux équipes sur demi-terrain, sans dribble : 10 passes d\'affilée sans perte = 1 point.', 'Se démarquer juste après la passe\nPasse appuyée à deux mains\nCompter à voix haute', 'Chasubles, 1 ballon', '', ''],
      ['echauffement', 'Activation avec ballon autour du corps', 8, 'Chacun son ballon : tours de taille, de tête, entre les jambes, puis dribbles bas sur place.', 'Doigts écartés, pas la paume\nRegarder devant soi\nAccélérer peu à peu', '1 ballon par joueur', '', ''],
      ['dribble', 'Dribble à deux ballons', 10, 'Chacun deux ballons sur la longueur : dribbles simultanés, puis alternés, puis en marchant vite.', 'Dribble bas et fort\nTête haute\nMain faible aussi forte que l\'autre', '2 ballons par joueur', '', ''],
      ['dribble', 'Le chat et la souris en dribble', 8, 'Dans la raquette puis sur demi-terrain : un chat sans ballon touche les dribbleurs, le joueur touché devient chat.', 'Protéger le ballon avec le corps\nChanger de main loin du chat\nNe jamais arrêter le dribble', '1 ballon par joueur, plots', '', ''],
      ['dribble', 'Le roi du cercle', 10, 'Tous dans le rond central puis dans la raquette : chacun dribble et essaie de faire sortir le ballon des autres.', 'Bras libre pour se protéger\nDribble bas près du corps\nVoir tout le monde', '1 ballon par joueur', '', ''],
      ['dribble', 'Changements de rythme ligne à ligne', 10, 'Sur la longueur : lent jusqu\'au lancer franc, explosion jusqu\'au milieu, freinage, nouvelle accélération.', 'Le premier pas fait la différence\nFreiner sur deux appuis\nGarder le contrôle', '1 ballon par joueur', '', ''],
      ['passe', 'Passes variées sur la longueur', 10, 'Par 2 sur la longueur en pas chassés : passes poitrine, à rebond, par-dessus la tête, puis à une main.', 'Passe sur la cible (les mains du partenaire)\nPasse à rebond aux deux tiers de la distance\nRecevoir en avançant vers le ballon', '1 ballon pour 2', '', ''],
      ['passe', 'La tresse à 3', 12, 'Trois colonnes sur la ligne de fond : on monte en se passant le ballon, celui qui passe court derrière celui qui reçoit. Double pas au bout.', 'Passe devant le receveur, dans sa course\nCourir derrière le receveur\nAucun dribble', 'Ballons', '', ''],
      ['passe', 'Rondo 4 contre 1', 10, 'Carré de 5 m : 4 attaquants sur les côtés, 1 défenseur au milieu. Passe interceptée = on change de défenseur.', 'Feinte de passe avant de passer\nPasse vite, sans dribble\nSe déplacer sur son côté pour offrir une ligne', 'Plots, 1 ballon', '', ''],
      ['tir', 'Tir après réception (catch and shoot)', 12, 'Un passeur sous le panier, le tireur part du coin et vient recevoir à 45° prêt à tirer : 5 tirs puis on tourne.', 'Mains prêtes avant la réception\nPieds déjà orientés vers le panier\nMême geste à chaque tir', 'Ballons', '', ''],
      ['tir', 'Le tour du monde', 12, '7 positions autour de la raquette : on avance d\'une position à chaque panier, le premier qui fait le tour gagne.', 'Routine identique\nBras qui finit vers le cercle\nRebond suivi par le partenaire', 'Ballons', '', ''],
      ['tir', 'Tir en suspension après dribble', 12, 'Départ du milieu de terrain : 2 dribbles d\'attaque, arrêt sur deux pieds au coude de la raquette, tir.', 'Arrêt équilibré avant de monter\nMonter droit, pas vers l\'avant\nLâcher en haut du saut', 'Ballons, plots', '', ''],
      ['tir', 'Lancers francs dans la fatigue', 10, 'Sprint aller-retour sur la largeur, puis 2 lancers francs. Chaque raté = un aller-retour de plus pour l\'équipe.', 'Respirer avant la routine\nToujours les mêmes gestes\nCoude sous le ballon', 'Ballons', '', ''],
      ['tir', 'Finitions sous le panier en continu', 10, 'Sous le panier : main droite côté droit, main gauche côté gauche, sans laisser tomber le ballon, 30 secondes.', 'Utiliser la planche\nPied d\'appel opposé à la main\nRythme régulier', 'Ballons', '', ''],
      ['un', '1 contre 1 tout terrain en couloir', 12, 'Couloir d\'un tiers de la largeur : l\'attaquant remonte tout le terrain en dribble, le défenseur l\'oriente vers la ligne.', 'Attaquant : changements de main et de rythme\nDéfenseur : un bras d\'avance, pas glissés\nFinir au panier', 'Ballons, plots', '', ''],
      ['un', '1 contre 1 au poste bas', 12, 'Le pivot se démarque au poste bas, reçoit d\'un passeur à l\'aile, puis 1 contre 1 dos au panier.', 'Prendre position avec le bassin\nRegarder le défenseur par-dessus l\'épaule\nPivot puis tir ou crochet', 'Ballons', '', ''],
      ['defense', 'Fermer la ligne de fond', 12, 'L\'attaquant reçoit au coin et veut passer par la ligne de fond, le défenseur l\'oblige à rentrer vers l\'aide.', 'Pied extérieur en avant\nNe jamais laisser la ligne de fond\nAide qui arrive de la raquette', 'Ballons', '', ''],
      ['defense', 'Défendre l\'écran : passer devant ou derrière', 15, '2 contre 2 sur un écran porteur : le coach annonce la défense (passer devant, derrière, ou changer).', 'Annoncer l\'écran à voix haute\nLe défenseur de l\'écran montre sa main\nRevenir chacun sur son joueur', 'Chasubles, ballons', '', ''],
      ['defense', 'Sortir sur le tireur (close-out)', 10, 'Le défenseur sous le panier passe le ballon au tireur à l\'aile et sort sur lui : contester le tir sans se faire déborder.', 'Sprint puis petits pas\nUne main haute devant le ballon\nRester entre le joueur et le panier', 'Ballons', '', ''],
      ['rebond', 'Rebond offensif à 3 contre 3', 12, 'Le coach tire : 3 défenseurs bloquent, 3 attaquants contournent pour prendre le rebond. Rebond offensif = 2 points.', 'Attaquant : ne jamais rester bloqué, faire le tour\nDéfenseur : contact puis ballon\nPrendre le ballon à deux mains', 'Chasubles, ballons', '', ''],
      ['transitions', 'Jeu rapide sur passe du rebondeur', 15, 'Le coach tire et rate exprès : le rebondeur passe vite à l\'aile, trois joueurs montent dans les couloirs et finissent en moins de 6 secondes.', 'Passe de sortie au-dessus de la tête\nOccuper trois couloirs\nLe ballon va plus vite que le dribble', 'Ballons', '', ''],
      ['transitions', '4 contre 4 avec retour défensif', 15, 'Après un tir, l\'équipe qui défendait attaque tout de suite l\'autre panier : 4 contre 4 en continu.', 'Revenir d\'abord protéger le panier\nTrouver son joueur en courant\nAttaque rapide si la défense n\'est pas en place', 'Chasubles, ballons', 'b5', ''],
      ['attaque', 'Passe et coupe', 12, '2 contre 2 sur demi-terrain : le passeur coupe tout de suite vers le panier, il reçoit en retour s\'il gagne sa course.', 'Changer de vitesse dans la coupe\nMain cible pour réclamer\nRemplir la place laissée', 'Ballons', '', ''],
      ['attaque', 'Écran sans ballon à 3 contre 3', 15, 'Demi-terrain : le joueur sans ballon pose un écran pour un partenaire qui se démarque vers l\'aile pour recevoir et tirer.', 'Écran immobile, pieds écartés\nAttendre l\'écran avant de partir\nL\'écraneur se rend disponible après', 'Chasubles, ballons', '', ''],
      ['jeu', '3x3 : le gagnant reste', 15, 'Un panier, matchs de 3 minutes ou jusqu\'à 7 points : l\'équipe qui gagne reste, une nouvelle entre.', 'Ressortir derrière l\'arc après un rebond défensif\nJouer vite : 12 secondes pour tirer\nParler en défense', 'Chasubles, ballons', 'b3', ''],
      ['jeu', '5 contre 5 : trois passes avant de tirer', 20, 'Match sur tout le terrain : chaque attaque doit faire 3 passes avant le tir, sauf en contre-attaque.', 'Écarter le jeu\nBouger après avoir passé\nDéfense qui parle', 'Chasubles', 'b5', ''],
      ['physique', 'Gainage et pas défensifs', 10, 'Ateliers de 30 s : planche, pas glissés entre deux plots, sauts latéraux, sprints de 5 m.', 'Dos droit\nAppuis courts\nRécupérer entre les ateliers', 'Plots, tapis', '', ''],
      ['calme', 'Tirs de près et respiration', 8, 'Par 2 : tirs à 2 m du panier en marchant, puis respiration lente et étirements des mollets et des épaules.', 'Tir doux, de la planche\nSouffler longuement\nÉtirer sans à-coups', 'Ballons', '', ''],
    ],
    hand: [
      ['echauffement', 'Balle au capitaine', 10, 'Deux équipes sur demi-terrain, un capitaine dans une zone de chaque côté : 5 passes puis une passe au capitaine = 1 point.', 'Se démarquer dans les espaces libres\n3 pas, 3 secondes\nPasser vite à celui qui est libre', 'Chasubles, plots, 1 ballon', '', ''],
      ['echauffement', 'Échauffement des épaules', 8, 'Par 2 à 6 m : passes à deux mains, puis à une main de plus en plus fortes, puis passes en sautant.', 'Monter progressivement\nCoude haut au moment de lancer\nRécupérer en souplesse', '1 ballon pour 2', '', ''],
      ['technique', 'Navettes de passes en course', 10, 'Deux colonnes face à face à 15 m : on court vers l\'autre colonne en recevant et en passant dans la course.', 'Recevoir bras tendus devant\nPasser sans s\'arrêter\nRespecter les 3 pas', 'Ballons', '', ''],
      ['technique', 'Réception en course et 3 pas', 10, 'Le joueur court sur l\'aile, reçoit d\'un passeur au centre, fait ses 3 pas et passe au suivant.', 'Compter les appuis\nLever le bras tôt\nGarder la vitesse', 'Ballons, plots', '', ''],
      ['technique', 'Passes variées : à rebond, en cloche, dans le dos', 10, 'Par 3 en triangle de 6 m : chaque joueur enchaîne les passes demandées par le coach.', 'Passe à rebond près du receveur\nPasse en cloche au-dessus d\'un bras levé\nPrécision avant force', '1 ballon pour 3', '', ''],
      ['technique', 'Dribble et changements de direction', 8, 'Slalom entre 6 plots en dribble, puis passe au suivant.', 'Ballon devant le corps\nDribble à hauteur de hanche\nRegarder devant', 'Plots, ballons', '', ''],
      ['tir', 'Tir de l\'aile en angle fermé', 12, 'Une colonne à chaque aile : réception, plongée vers le but, tir en s\'ouvrant l\'angle.', 'Sauter vers l\'intérieur pour ouvrir l\'angle\nViser le premier poteau ou le côté opposé\nRegarder le gardien', 'Ballons', '', ''],
      ['tir', 'Tir du pivot dos au but', 12, 'Le pivot se démarque entre deux plots, reçoit dos au but, pivote et tire.', 'Recevoir près du corps\nPivoter côté libre\nTirer vite, près de la zone', 'Ballons, plots', '', ''],
      ['tir', 'Jet de 7 mètres', 8, 'Chacun tire 3 penaltys face au gardien, puis les tireurs changent de place de tir.', 'Pied d\'appui fixe derrière la ligne\nChoisir son coin avant\nRegarder le gardien, pas le coin', 'Ballons', '', ''],
      ['tir', 'Tir en suspension avec feinte', 12, 'Arrière à 10 m : feinte de tir en appui, deux pas d\'accélération, tir en suspension.', 'Feinte crédible, bras armé\nImpulsion vers le haut\nTir puis réception sur deux pieds', 'Ballons', '', ''],
      ['un', '1 contre 1 de l\'arrière', 12, 'L\'arrière reçoit à 10 m face à un défenseur : feinte d\'un côté, débordement de l\'autre et tir.', 'Feinte avec le corps entier\nAccélérer dans l\'intervalle\nProtéger le ballon du bras extérieur', 'Ballons', '', ''],
      ['un', '2 contre 2 arrière et pivot', 15, 'L\'arrière et le pivot contre deux défenseurs : jeu de bloc, passe au pivot ou tir de l\'arrière.', 'Le pivot bloque le défenseur de l\'arrière\nL\'arrière fixe avant de passer\nLire où va la défense', 'Chasubles, ballons', '', ''],
      ['defense', 'Monter sur le tireur et revenir', 12, 'Le défenseur sur la zone sort sur l\'arrière qui reçoit à 9 m, l\'empêche de tirer, puis recule quand le ballon part.', 'Sortir bras levé\nContact sur le bras de tir\nRevenir vite à sa place', 'Ballons', '', ''],
      ['defense', 'Défendre l\'intervalle', 12, 'Trois défenseurs contre trois attaquants : la défense ferme les intervalles et dissuade la passe.', 'Se placer côté ballon\nAider le partenaire qui sort\nCommuniquer', 'Chasubles, ballons', '', ''],
      ['defense', 'Contre du défenseur', 10, 'Le défenseur face au tireur en suspension saute bras tendus pour contrer, le gardien couvre l\'autre côté.', 'Sauter au bon moment\nBras collés, mains ouvertes\nSe partager le but avec le gardien', 'Ballons', '', ''],
      ['gardien', 'Gardien : déplacements et réflexes', 10, 'Le coach lance des ballons à droite, à gauche, en haut, en bas : le gardien se déplace et arrête.', 'Appuis légers, sur l\'avant du pied\nBras et jambe ensemble du même côté\nSe relever tout de suite', 'Ballons', '', ''],
      ['gardien', 'Gardien : relance rapide', 10, 'Après chaque arrêt, le gardien relance vers l\'ailier qui part en contre-attaque.', 'Regarder avant de relancer\nPasse longue tendue, devant l\'ailier\nRelancer en moins de 3 secondes', 'Ballons', '', ''],
      ['transitions', 'Repli défensif après la perte', 12, 'Attaque à 4 contre 4 : à la perte, tout le monde sprinte se replacer en défense, le coach compte 5 secondes.', 'Sprinter d\'abord, regarder ensuite\nLe plus proche gêne le porteur\nSe replacer à 6 m', 'Chasubles, ballons', '', ''],
      ['transitions', 'Contre-attaque des deux ailiers', 12, 'Le gardien arrête, les deux ailiers partent : passe longue à l\'un, puis 2 contre 1 contre le défenseur qui revient.', 'Partir dès l\'arrêt\nRester large\nFinir avant que la défense revienne', 'Ballons', '', ''],
      ['attaque', 'Circulation de balle à 6 contre 0', 10, 'Les 6 attaquants en place : le ballon circule de l\'ailier à l\'autre ailier, chacun attaque l\'intervalle avant de passer.', 'Attaquer le but avant de passer\nPasse dans la course\nRythme qui accélère', 'Ballons', '', ''],
      ['attaque', 'Croisé ailier-arrière', 12, 'L\'ailier rentre vers le centre et croise derrière l\'arrière : 2 contre 2 puis tir.', 'L\'ailier part au bon moment\nPasse courte et protégée\nAttaquer l\'espace libéré', 'Ballons', '', ''],
      ['attaque', 'Bloc du pivot', 15, 'Le pivot bloque le défenseur de l\'arrière : l\'arrière passe du côté du bloc, puis 3 contre 3.', 'Bloc immobile, bien appuyé\nL\'arrière frôle le pivot\nLe pivot se retourne pour recevoir', 'Chasubles, ballons', '', ''],
      ['jeu', 'Match à thème : but de l\'aile = 2 points', 20, 'Match à 7 contre 7 : un but marqué par un ailier compte double.', 'Écarter le jeu jusqu\'aux ailes\nFixer au centre pour libérer l\'aile\nAiliers prêts à recevoir', 'Chasubles', 'h7', ''],
      ['jeu', 'Match à 4 contre 4 + gardiens', 15, 'Petit terrain en largeur, deux buts : relance rapide du gardien obligatoire.', 'Jouer vite\nSoutien proche du porteur\nRepli immédiat à la perte', 'Chasubles, 2 buts', '', ''],
      ['physique', 'Navettes et sauts', 10, 'Navettes 6 m - 9 m - 6 m, puis 5 sauts au-dessus de petites haies, 4 séries.', 'Freiner sur deux appuis\nSauter loin, pas haut\nRécupérer en marchant', 'Plots, haies basses', '', ''],
      ['calme', 'Passes en marchant et étirements des épaules', 8, 'Par 2 en marchant, passes à deux mains, puis étirements des épaules, du dos et des jambes.', 'Respirer\nÉtirer sans à-coups\nBoire', 'Ballons', '', ''],
    ],
    rugby: [
      ['echauffement', 'Béret rugby', 10, 'Deux équipes face à face, un ballon au centre : le coach appelle des numéros, le joueur qui prend le ballon doit revenir sans être touché.', 'Réagir vite\nProtéger le ballon\nFeinter pour passer', 'Plots, 1 ballon', '', ''],
      ['echauffement', 'Passes en cercle et déplacement', 8, 'En cercle de 8 joueurs : passes à droite, à gauche, puis on change de place après avoir passé.', 'Mains prêtes devant la poitrine\nPasse vers le partenaire, pas au hasard\nAppeler le ballon', '1 à 2 ballons', '', ''],
      ['passe', 'Passe et redoublement (boucle)', 12, 'Par 3 sur 20 m : le passeur fait le tour derrière le receveur et revient recevoir à l\'extérieur.', 'Passer puis courir tout de suite\nRedoubler près du receveur\nRecevoir lancé', 'Ballons, plots', '', ''],
      ['passe', 'Passes sous pression : 4 contre 2 dans un carré', 12, 'Carré de 15 m : 4 attaquants se passent le ballon au toucher, 2 défenseurs essaient de toucher le porteur.', 'Passer avant d\'être touché\nSoutien de chaque côté du porteur\nPasses courtes et précises', 'Plots, 1 ballon', '', ''],
      ['passe', 'Passe après contact', 12, 'Le porteur va au contact d\'un bouclier, garde les bras libres et passe au soutien qui arrive.', 'Contact épaule, ballon protégé\nBras libres au-dessus du défenseur\nLe soutien arrive lancé', 'Boucliers, ballons', '', ''],
      ['pied', 'Coup de pied de transition et poursuite', 12, 'Le botteur tape devant lui à 20 m, ses partenaires poursuivent en ligne pour mettre la pression sur le receveur.', 'Les poursuivants partent derrière le botteur\nMonter en ligne\nPlaquer ou bloquer le receveur', 'Ballons', '', ''],
      ['pied', 'Réception de chandelle', 10, 'Le coach tape des chandelles : le receveur annonce « à moi », saute ou reçoit sur un pied, protège le ballon.', 'Annoncer fort\nBras en corbeille, coude serré\nSe retourner vers ses partenaires', 'Ballons', '', ''],
      ['pied', 'Coup d\'envoi et renvoi aux 22 mètres', 12, 'Un botteur au centre, une ligne de poursuivants : on vise une zone, l\'autre équipe s\'organise pour réceptionner.', 'Viser une zone, pas un joueur\nPoursuivre ensemble\nLe receveur est protégé par ses partenaires', 'Ballons', '', ''],
      ['plaquage', 'Plaquage à genoux', 10, 'Par 2, les deux à genoux : le plaqueur met la joue contre la fesse du porteur, entoure les cuisses et le fait tomber sur le côté.', 'Tête sur le côté, jamais devant\nSerrer les bras\nAccompagner au sol', 'Tapis', 'r10', ''],
      ['plaquage', 'Plaquage sur un porteur qui marche', 12, 'Le porteur marche vers le plaqueur, qui s\'approche à petits pas, se baisse et plaque aux cuisses.', 'Petits pas avant le contact\nÉpaule dans les cuisses\nPieds qui continuent d\'avancer', 'Ballons, boucliers', '', ''],
      ['plaquage', 'Double plaquage haut et bas', 12, 'Deux défenseurs contre un porteur : le premier plaque bas, le second ceinture le ballon.', 'Le premier part bas\nLe second vise le ballon\nSe parler avant le contact', 'Ballons, boucliers', 'r15,r7', ''],
      ['plaquage', 'Défense : pousser vers la touche', 12, 'Quatre défenseurs contre cinq attaquants : la ligne glisse et pousse l\'attaque vers la touche.', 'Monter ensemble\nL\'extérieur ferme le couloir\nChacun prend son vis-à-vis', 'Plots, ballons', '', ''],
      ['contact', 'Maul : construire et avancer', 15, 'Après la réception d\'une touche, les avants se lient autour du porteur et poussent ensemble sur 10 m.', 'Se lier fermement\nBas et groupés\nLe ballon passe vers l\'arrière du maul', 'Boucliers, ballons', 'r15', ''],
      ['contact', 'Rester debout au contact', 12, 'Le porteur va au contact d\'un bouclier, reste sur ses pieds et présente le ballon à son soutien.', 'Appuis larges\nÉpaule basse\nBallon loin du défenseur', 'Boucliers, ballons', '', ''],
      ['conquete', 'Mêlée à 3 : liaison et poussée', 12, 'Trois contre trois sur les genoux puis debout : se lier, prendre position, pousser au signal.', 'Dos plat\nTête haute\nPousser ensemble au signal', 'Tapis', 'r15,r10', ''],
      ['conquete', 'Touche courte et touche longue', 12, 'Le lanceur et trois sauteurs : le capitaine annonce le code, touche au premier sauteur ou au fond.', 'Code annoncé avant le lancer\nLancer tendu\nSauteur soulevé au bon moment', 'Ballons', 'r15,r7', ''],
      ['soutien', 'Soutien intérieur après une percée', 12, 'Le porteur perce entre deux plots, le soutien arrive à l\'intérieur pour recevoir la passe.', 'Le soutien suit le porteur\nAppeler le ballon\nPasse courte à l\'intérieur', 'Plots, ballons', '', ''],
      ['soutien', 'Ruck rapide : deux arrivées au soutien', 12, 'Le porteur va au sol, deux soutiens nettoient le ruck, le demi de mêlée sort le ballon.', 'Arriver bas, bras dans le ruck\nPousser au-delà du ballon\nBallon dégagé en moins de 3 secondes', 'Boucliers, ballons', '', ''],
      ['attaque', 'Le cadrage-débordement', 12, 'Couloir de 15 m : le porteur fixe son défenseur vers l\'intérieur puis accélère à l\'extérieur.', 'Attaquer l\'épaule intérieure\nChanger d\'appui au dernier moment\nAccélérer après le changement', 'Plots, ballons', '', ''],
      ['attaque', 'Croisée et passe décalée', 12, 'Trois attaquants : croisée entre les deux premiers, puis passe à l\'extérieur.', 'Courses qui se croisent près\nPasse courte, protégée\nLire le défenseur', 'Plots, ballons', '', ''],
      ['attaque', 'Jeu à partir d\'un ruck', 15, 'Après un ruck, le demi de mêlée passe à l\'ouvreur, qui choisit : jouer au large, au pied ou avec un avant.', 'Demi de mêlée : sortie rapide\nOuvreur : lire la défense\nLes avants se replacent pour le temps suivant', 'Plots, ballons', 'r15', ''],
      ['jeu', 'Match à 5 contre 5 au toucher', 15, 'Petit terrain : au toucher, le porteur pose le ballon et un partenaire le relève. 6 touchers = ballon rendu.', 'Écarter le jeu\nSoutien des deux côtés\nDéfense qui monte ensemble', 'Chasubles, plots', '', ''],
      ['jeu', 'Match à thème : l\'essai vaut double après 3 passes', 20, 'Match au contact adapté : un essai après au moins 3 passes compte double.', 'Faire vivre le ballon\nSoutien proche\nPatience avant d\'accélérer', 'Chasubles', '', ''],
      ['physique', 'Navettes et relevés du sol', 10, 'Course 10 m, plaquage au sol simulé, relevé, course 10 m : 6 répétitions.', 'Se relever vite\nRepartir sur l\'avant du pied\nRécupérer entre les séries', 'Plots', '', ''],
      ['physique', 'Lutte et gainage par deux', 8, 'Par 2 de même gabarit : lutte pour le ballon au sol, gainage de face et de côté.', 'Rester gainé\nRespecter son partenaire\nRespirer', 'Tapis, ballons', '', ''],
    ],
    volley: [
      ['echauffement', 'Balle brûlante à la main', 8, 'Deux équipes de part et d\'autre du filet : on se renvoie le ballon à la main, il ne doit jamais toucher le sol.', 'Se déplacer avant que le ballon arrive\nRenvoyer vers un espace vide\nSe parler', 'Filet, 1 ou 2 ballons', '', ''],
      ['echauffement', 'Épaules et poignets avec ballon', 8, 'Chacun son ballon : rotations des bras, frappes contre le mur à une main, échanges légers par deux.', 'Monter progressivement\nPoignet souple\nÉpaules bien échauffées avant de frapper', '1 ballon par joueur', '', ''],
      ['technique', 'Touche haute en déplacement', 10, 'Par 2 : l\'un envoie en avant, sur le côté, en arrière, l\'autre se déplace et renvoie en touche.', 'Arriver sous le ballon avant qu\'il descende\nMains en coupe au-dessus du front\nJambes qui poussent', '1 ballon pour 2', '', ''],
      ['technique', 'Manchette en déplacement latéral', 10, 'Le coach lance à droite et à gauche, le joueur se déplace en pas chassés et renvoie en manchette vers la cible.', 'Pas chassés, pas croisés\nBras tendus, plan stable\nOrienter les épaules vers la cible', 'Ballons, cible', '', ''],
      ['technique', 'Passe arrière en touche', 10, 'Par 3 en ligne : le joueur du milieu reçoit de face et passe en arrière par-dessus sa tête.', 'Ballon au-dessus du front\nCambrer légèrement\nBras qui finissent vers l\'arrière', '1 ballon pour 3', '', ''],
      ['technique', 'Jonglages assis-debout', 8, 'En jonglant en touche : s\'asseoir, se relever, sans laisser tomber le ballon.', 'Ballon haut\nSe relever en gardant les yeux sur le ballon\nGestes doux', '1 ballon par joueur', '', ''],
      ['service', 'Service cuillère', 10, 'À 3 m du filet puis de plus en plus loin : service par en dessous vers le terrain adverse.', 'Lancer bas, devant\nFrapper avec la base de la main\nBras qui finit vers la cible', 'Ballons, filet', 'v4', ''],
      ['service', 'Service tennis flottant', 12, 'Derrière la ligne de fond : service tennis sans rotation du ballon, vers une zone annoncée.', 'Lancer devant l\'épaule de frappe\nMain ferme, frappe sèche au centre du ballon\nNe pas accompagner le geste', 'Ballons, filet', '', ''],
      ['service', 'Service sous pression : 10 sur 10', 10, 'Chaque joueur doit réussir 10 services de suite dans le terrain ; un raté, on recommence à zéro.', 'Même routine à chaque service\nRespirer avant de lancer\nViser large, pas les lignes', 'Ballons, filet', '', ''],
      ['reception', 'Réception à deux sur service flottant', 12, 'Deux réceptionneurs se partagent le terrain, un serveur en face : la réception vise le passeur.', 'Annoncer « j\'ai » tôt\nÊtre arrêté avant la frappe\nPlan de frappe vers le passeur', 'Ballons, filet', '', ''],
      ['reception', 'Réception puis attaque', 15, 'Service, réception, passe, attaque : le réceptionneur va ensuite attaquer en zone 4.', 'Réception haute et au centre\nSe replacer vite pour l\'élan\nEnchaîner sans pause', 'Ballons, filet', '', ''],
      ['attaque', 'Attaque en zone 2', 12, 'Le passeur en zone 3 passe en arrière vers la zone 2, l\'attaquant prend son élan et frappe.', 'Élan en 3 temps\nFrapper le ballon devant soi\nViser la diagonale ou la ligne', 'Ballons, filet', '', ''],
      ['attaque', 'Attaque de la zone arrière', 12, 'L\'attaquant part de la zone 6, saute avant la ligne des 3 m et frappe un ballon haut.', 'Sauter avant la ligne\nFrapper au-dessus du ballon\nRetomber et revenir défendre', 'Ballons, filet', 'v6', ''],
      ['attaque', 'Feinte et balle placée', 10, 'L\'attaquant prend son élan comme pour frapper puis place le ballon derrière le contre, du bout des doigts.', 'Même élan que pour frapper\nPoser au dernier moment\nViser l\'espace vide', 'Ballons, filet', '', ''],
      ['contre', 'Contre seul : lire le passeur', 12, 'Le contreur regarde le passeur, se déplace vers l\'attaquant servi et saute au moment de la frappe.', 'Regarder passeur puis attaquant\nSauter juste après l\'attaquant\nMains au-dessus du filet, vers l\'intérieur', 'Ballons, filet', '', ''],
      ['contre', 'Contre et retour en couverture', 12, 'Après le contre, le contreur se retourne et se place pour défendre ou couvrir son attaquant.', 'Retomber sur deux pieds\nSe retourner vers le ballon\nDescendre vite en position basse', 'Ballons, filet', '', ''],
      ['defense', 'Défense et relance en manchette', 12, 'Le coach attaque depuis une chaise de l\'autre côté, le défenseur remonte le ballon haut vers le centre.', 'Position basse avant la frappe\nBras sous le ballon\nBallon haut et au centre', 'Ballons, chaise, filet', '', ''],
      ['defense', 'Couvrir son attaquant', 12, 'Quand l\'attaquant frappe, les autres se rapprochent en arc de cercle pour reprendre un ballon contré.', 'Se rapprocher bas\nBras prêts\nRelancer haut pour une nouvelle attaque', 'Ballons, filet', '', ''],
      ['defense', 'Plongeon et roulade', 10, 'Sur tapis : le coach lance un ballon loin, le joueur plonge ou roule pour le remonter.', 'Se lancer bas\nAmortir avec les bras ou en roulant\nRemonter le ballon avant de tomber', 'Tapis, ballons', '', ''],
      ['jeu', 'Match à 2 contre 2', 15, 'Petit terrain : deux contre deux, trois touches obligatoires.', 'Se parler à chaque ballon\nCouvrir tout le terrain à deux\nAttaquer les espaces', 'Ballons, filet', '', ''],
      ['jeu', 'Match à 6 avec rotation obligatoire', 20, 'Match normal à 6 : à chaque point gagné au service, l\'équipe tourne, chacun passe à tous les postes.', 'Connaître sa place à chaque rotation\nRéception au passeur\nConstruire avant d\'attaquer', 'Ballons, filet', 'v6', ''],
      ['jeu', 'Le roi du terrain', 15, 'Une équipe « roi » d\'un côté : les équipes qui attendent servent ; si elles gagnent le point, elles prennent la place du roi.', 'Concentration à chaque ballon\nService sûr\nSe parler', 'Ballons, filet', '', ''],
      ['physique', 'Sauts sur banc et réception', 10, 'Sauts à deux pieds sur un banc bas, puis réception et saut bras tendus vers le filet : 4 séries de 6.', 'Atterrir souple, genoux dans l\'axe\nBras qui aident le saut\nQualité avant quantité', 'Bancs bas', '', ''],
      ['physique', 'Déplacements défensifs en étoile', 8, 'Au centre d\'une étoile de 5 plots : aller toucher chaque plot en position basse et revenir.', 'Rester bas\nPetits pas rapides\nRegarder devant', 'Plots', '', ''],
      ['calme', 'Services de précision et respiration', 8, 'Services doux vers des cerceaux posés au sol, puis respiration et étirements des épaules.', 'Geste lent et précis\nSouffler longuement\nÉtirer sans à-coups', 'Ballons, cerceaux', '', ''],
    ],
  };
  const SES = {
    basket: [
      { sys: 'Jeu 3x3', fmt: 'b3', title: 'Le 3x3 : jouer vite et ressortir', goal: 'Ressortir derrière l\'arc après chaque rebond défensif, attaquer en moins de 12 secondes.', ex: [
        ['transitions', 'Rebond et ressortie derrière l\'arc', 12, 'Le coach tire : le rebondeur ressort en dribble ou en passe derrière l\'arc avant d\'attaquer.', 'Ressortir les deux pieds derrière l\'arc|Passe de sortie rapide|Attaquer tout de suite', 'Ballons', ''],
        ['attaque', 'Écran porteur à 2 contre 2 sur un panier', 15, 'Deux contre deux sur le panier du 3x3 : écran, lecture, tir ou passe.', 'Écran solide|Lire le défenseur de l\'écran|Le troisième se rend disponible', 'Ballons', ''],
        ['jeu', '3x3 : matchs à 21 points', 20, 'Matchs à 21 points ou 10 minutes, règles du 3x3 (1 point / 2 points derrière l\'arc).', 'Shot-clock de 12 secondes|Pas de temps mort en défense|Parler', 'Chasubles', '']] },
      { sys: 'Défense 3x3', fmt: 'b3', title: 'Défendre à 3 en 3x3', goal: 'Défendre fort sur le porteur, changer sur les écrans, prendre le rebond.', ex: [
        ['defense', 'Pression sur le porteur à 1 contre 1', 10, 'L\'attaquant part de l\'arc, le défenseur l\'empêche d\'entrer dans la raquette.', 'Pas glissés|Bras actifs|Orienter vers la ligne', 'Ballons', ''],
        ['defense', 'Changer sur l\'écran', 12, '2 contre 2 : sur chaque écran, les défenseurs changent de joueur en l\'annonçant.', 'Annoncer « change »|Le nouveau défenseur se colle tout de suite|Aucun espace pour tirer', 'Ballons', ''],
        ['jeu', '3x3 : un arrêt défensif = 1 point', 15, 'Match 3x3 : une défense qui récupère le ballon sans encaisser marque 1 point.', 'Défense agressive|Rebond à deux mains|Ressortir vite', 'Chasubles', '']] },
      { sys: 'Passe et coupe', fmt: 'b5', title: 'Attaquer l\'homme à homme sans écran', goal: 'Bouger après chaque passe : couper vers le panier, remplir les places.', ex: [
        ['attaque', 'Passe et coupe à 2 contre 2', 12, 'Le passeur coupe vers le panier après sa passe, il reçoit s\'il gagne sa course.', 'Changer de vitesse|Main cible|Remplir la place vide', 'Ballons', ''],
        ['attaque', 'Remplir les places à 4 contre 4', 15, 'Demi-terrain, 4 extérieurs : chaque coupe libère une place, le joueur le plus proche la remplit.', 'Une coupe, un remplacement|Espaces de 4 à 5 m|Passe dans la coupe', 'Chasubles, ballons', ''],
        ['jeu', '5 contre 5 sans dribble en demi-terrain', 15, 'Demi-terrain : l\'attaque n\'a pas le droit de dribbler, seulement des passes et des coupes.', 'Bouger sans ballon|Passes rapides|Feintes de passe', 'Chasubles', '']] },
      { sys: 'Jeu intérieur', fmt: 'b5', title: 'Faire jouer les intérieurs au poste bas', goal: 'Donner le ballon au pivot et jouer autour de lui (tir, ressortie).', ex: [
        ['un', '1 contre 1 au poste bas', 12, 'Le pivot reçoit dos au panier et joue son 1 contre 1.', 'Prendre position|Sentir le défenseur|Pivot puis finition', 'Ballons', ''],
        ['passe', 'Entrée de balle au poste bas', 10, 'L\'ailier passe au pivot par-dessus ou à côté du défenseur, puis se replace pour une ressortie.', 'Passe du côté où le pivot montre la main|Feinter avant|Se replacer après', 'Ballons', ''],
        ['jeu', '4 contre 4 : le pivot doit toucher le ballon', 15, 'Demi-terrain : avant chaque tir, le ballon doit passer par le poste bas.', 'Patience|Jeu intérieur-extérieur|Tir ouvert après ressortie', 'Chasubles, ballons', '']] },
      { sys: 'Zone 1-3-1', fmt: 'b5', title: 'Défense de zone 1-3-1', goal: 'Un devant, trois au milieu, un derrière : piéger le porteur dans les coins.', ex: [
        ['defense', 'Placement en 1-3-1 sans ballon', 10, 'Les 5 défenseurs se placent, le coach déplace le ballon : la zone glisse et piège dans les coins.', 'Le haut oriente vers le côté|Le bas couvre la ligne de fond|Piège à deux dans le coin', 'Ballon', ''],
        ['defense', 'Zone 1-3-1 contre 5 attaquants', 18, 'Demi-terrain : l\'attaque fait circuler, la défense cherche le piège et l\'interception.', 'Bras tendus dans les lignes de passe|Se parler|Rebond défensif', 'Chasubles, ballons', ''],
        ['jeu', 'Match avec zone 1-3-1 obligatoire', 20, 'Match normal : chaque équipe défend en 1-3-1.', 'Communication|Rebond', 'Chasubles', '']] },
      { sys: 'Défense du pick and roll', fmt: 'b5', title: 'Défendre le jeu à deux', goal: 'Choisir sa défense sur l\'écran porteur et revenir sur son joueur.', ex: [
        ['defense', 'Montrer et revenir (hedge)', 12, 'Le défenseur de l\'écraneur sort devant le porteur pour le freiner, puis revient sur son joueur.', 'Sortir fort, bien en dehors|Revenir dès que le porteur ralentit|Le défenseur du porteur passe au-dessus', 'Ballons', ''],
        ['defense', 'Défense basse (drop)', 12, 'Le défenseur de l\'écraneur reste entre le porteur et le panier, sous l\'écran.', 'Protéger le panier|Le défenseur du porteur passe derrière l\'écran|Contester sans faute', 'Ballons', ''],
        ['jeu', '3 contre 3 avec écran porteur à chaque attaque', 15, 'Demi-terrain : chaque attaque commence par un écran porteur, la défense choisit sa réponse.', 'Annoncer la défense|Aide du troisième défenseur|Rebond', 'Chasubles, ballons', '']] },
      { sys: '4 extérieurs - 1 intérieur', fmt: 'b5', title: 'Écarter le jeu à 4 extérieurs', goal: 'Quatre joueurs autour de l\'arc, un intérieur : pénétrer et ressortir pour le tir ouvert.', ex: [
        ['tir', 'Tir après ressortie', 12, 'Un pénétrateur attire l\'aide et ressort vers le tireur à l\'aile ou au coin.', 'Tireur prêt, pieds placés|Passe dans les mains|Tirer sans hésiter', 'Ballons', ''],
        ['attaque', 'Pénétrer et ressortir à 4 contre 4', 15, 'Demi-terrain : chaque pénétration doit faire bouger l\'aide, le ballon ressort vers le joueur libre.', 'Attaquer le panier pour de vrai|Voir l\'aide|Se décaler pour recevoir', 'Chasubles, ballons', ''],
        ['jeu', '5 contre 5 : panier à 3 points = 4 points', 20, 'Match : un panier à 3 points après une ressortie compte 4 points.', 'Espacement|Patience|Rebond offensif', 'Chasubles', '']] },
      { sys: 'Remises en jeu', fmt: 'b5', title: 'Remises en jeu sous le panier', goal: 'Trois façons de remettre en jeu sous son panier et marquer vite.', ex: [
        ['attaque', 'Remise en jeu en boîte', 12, 'Quatre joueurs en carré dans la raquette : écrans croisés, le remiseur choisit le joueur libre.', 'Écrans au signal|Le remiseur lit la défense|5 secondes maximum', 'Ballons', ''],
        ['attaque', 'Remise en jeu en ligne', 12, 'Quatre joueurs alignés : ils partent chacun dans une direction au signal.', 'Départs simultanés|Une option près du panier|Une option de sécurité loin', 'Ballons', ''],
        ['jeu', 'Fins de match : 1 minute à jouer', 15, 'Situations : 2 points de retard, 1 minute, possession sous le panier. On rejoue plusieurs fois.', 'Garder son calme|Connaître le temps et le score|Faute ou pas faute : décider ensemble', 'Chasubles, chrono', '']] },
    ],
    hand: [
      { sys: 'Défense 4-2', fmt: 'h7', title: 'Défense 4-2 : deux avancés', goal: 'Deux défenseurs avancés gênent les arrières, quatre restent sur la zone.', ex: [
        ['defense', 'Les avancés gênent les arrières', 12, 'Deux défenseurs avancés à 9 m contre deux arrières qui se passent le ballon.', 'Gêner les passes|Rester entre le ballon et le but|Revenir quand le ballon passe à l\'aile', 'Ballons', ''],
        ['defense', 'Défense 4-2 contre 6 attaquants', 18, 'Les 6 défenseurs en 4-2 contre une attaque placée qui fait circuler.', 'Les quatre glissent ensemble|Les avancés coupent les passes|Communication', 'Chasubles, ballons', ''],
        ['jeu', 'Match avec défense 4-2', 20, 'Match à 7 contre 7 : chaque équipe défend en 4-2.', 'Organisation|Repli', 'Chasubles', '']] },
      { sys: 'Défense 3-3', fmt: 'h7', title: 'Défense 3-3 : très haute', goal: 'Trois défenseurs sur la zone, trois haut sur les arrières : récupérer vite.', ex: [
        ['defense', 'Pression sur les arrières à 3 contre 3', 12, 'Trois défenseurs hauts contre trois arrières : couper les passes, chercher l\'interception.', 'Défense haute|Bras dans les lignes de passe|Aider le voisin', 'Ballons', ''],
        ['transitions', 'Récupérer et contre-attaquer', 15, 'Chaque interception lance une contre-attaque immédiate vers l\'autre but.', 'Partir tout de suite|Passe vers l\'avant|Finir vite', 'Chasubles, ballons', ''],
        ['jeu', 'Match : une interception = 1 point', 20, 'Match à 7 contre 7 : chaque interception rapporte 1 point en plus.', 'Défense active|Repli', 'Chasubles', '']] },
      { sys: 'Défense individuelle', fmt: 'h7', title: 'Défense individuelle tout terrain', goal: 'Chacun son joueur sur tout le terrain : gêner la montée de balle.', ex: [
        ['defense', '1 contre 1 tout terrain', 10, 'Chaque défenseur suit un attaquant qui remonte le terrain en dribble.', 'Rester entre l\'attaquant et le but|Pas glissés|Intercepter si possible', 'Ballons', ''],
        ['defense', '3 contre 3 sur tout le terrain', 15, 'Trois contre trois en individuelle, l\'attaque doit traverser le terrain.', 'Coller son joueur|Couper les passes longues|Aide si le voisin est battu', 'Chasubles, ballons', ''],
        ['jeu', 'Match : individuelle les 5 dernières minutes', 20, 'Match normal : les 5 dernières minutes, l\'équipe menée défend en individuelle.', 'Changer d\'attitude au signal|Rester calme en attaque', 'Chasubles', '']] },
      { sys: 'Attaque contre 0-6', fmt: 'h7', title: 'Attaquer une défense 0-6', goal: 'Faire bouger une défense alignée sur la zone : fixer, passer, tirer de loin.', ex: [
        ['tir', 'Tirs de loin au-dessus de la défense', 12, 'Les arrières tirent en suspension à 9 m au-dessus d\'une ligne de défenseurs avec boucliers.', 'Impulsion haute|Tirer au-dessus des bras|Varier haut et bas', 'Boucliers, ballons', ''],
        ['attaque', 'Fixer et passer : 6 contre 6', 15, 'Chaque attaquant attaque son intervalle et passe au moment où deux défenseurs viennent sur lui.', 'Fixer deux défenseurs|Passer au joueur libre|Jeu à l\'aile en bout de chaîne', 'Chasubles, ballons', ''],
        ['jeu', 'Match contre défense 0-6', 20, 'Match : la défense doit rester en 0-6.', 'Patience|Tirs de loin|Jeu avec le pivot', 'Chasubles', '']] },
      { sys: 'Jeu avec les ailiers', fmt: 'h7', title: 'Faire marquer les ailiers', goal: 'Écarter la défense pour trouver l\'ailier en position de tir.', ex: [
        ['tir', 'Tir de l\'aile en angle fermé', 12, 'Une colonne à chaque aile : réception, plongée, tir.', 'S\'ouvrir l\'angle|Viser le premier poteau ou l\'autre côté|Regarder le gardien', 'Ballons', ''],
        ['attaque', 'Circulation jusqu\'à l\'aile', 12, 'Six contre six : le ballon circule vite d\'un ailier à l\'autre, chacun attaque avant de passer.', 'Passe dans la course|Attaquer le but|L\'ailier prêt à tirer', 'Chasubles, ballons', ''],
        ['jeu', 'Match : but de l\'aile = 2 points', 20, 'Match à 7 contre 7 : un but de l\'ailier compte double.', 'Largeur|Fixer au centre', 'Chasubles', '']] },
      { sys: 'Supériorité numérique', fmt: 'h7', title: 'Jouer à 7 contre 6 (gardien remplacé)', goal: 'Profiter du joueur en plus pour trouver un tir facile.', ex: [
        ['attaque', 'Placement à 7 joueurs de champ', 12, 'Sept attaquants contre six défenseurs : deux pivots, on cherche le joueur libre.', 'Écarter le jeu|Passe rapide vers le joueur libre|Ne pas se précipiter', 'Chasubles, ballons', ''],
        ['transitions', 'Revenir vite après une perte à 7 contre 6', 12, 'À la perte, le joueur en plus sort, le gardien revient : chacun sprinte se replacer.', 'Remplacement rapide|Protéger le but vide|Le plus proche gêne le tireur', 'Chasubles, ballons', ''],
        ['jeu', 'Match à thème : 7 contre 6 en fin de match', 15, 'Les 3 dernières minutes, l\'équipe menée joue à 7 contre 6.', 'Organisation|Sang-froid', 'Chasubles', '']] },
      { sys: 'Infériorité numérique', fmt: 'h7', title: 'Défendre à 5 (exclusion de 2 minutes)', goal: 'Tenir 2 minutes à 5 contre 6 sans encaisser.', ex: [
        ['defense', 'Défense à 5 sur la zone', 15, 'Cinq défenseurs contre six attaquants : la défense resserre l\'axe et laisse le tir difficile à l\'aile.', 'Resserrer l\'axe|Sortir seulement sur le porteur dangereux|Laisser l\'angle fermé', 'Chasubles, ballons', ''],
        ['attaque', 'Attaquer à 5 : garder le ballon', 12, 'Cinq attaquants contre six : garder le ballon longtemps et tirer seulement sûr.', 'Passes sûres|Utiliser le temps|Tir à coup sûr', 'Chasubles, ballons', ''],
        ['jeu', 'Match avec exclusions', 20, 'Match normal : le coach exclut un joueur 2 minutes de temps en temps.', 'S\'organiser vite|Se parler', 'Chasubles, chrono', '']] },
      { sys: 'Jeu du pivot', fmt: 'h7', title: 'Trouver le pivot', goal: 'Utiliser les blocs du pivot et lui donner le ballon près de la zone.', ex: [
        ['attaque', 'Bloc du pivot pour l\'arrière', 15, 'Le pivot bloque le défenseur de l\'arrière, l\'arrière passe du côté du bloc.', 'Bloc immobile|L\'arrière frôle le pivot|Le pivot se retourne pour recevoir', 'Ballons', ''],
        ['tir', 'Tir du pivot dos au but', 12, 'Le pivot reçoit dos au but entre deux plots, pivote et tire.', 'Recevoir près du corps|Pivoter côté libre|Tirer vite', 'Ballons, plots', ''],
        ['jeu', 'Match : but du pivot = 2 points', 20, 'Match à 7 contre 7 : un but du pivot compte double.', 'Jeu au pivot|Fixer avant de passer', 'Chasubles', '']] },
    ],
    rugby: [
      { sys: 'Rugby à 7 : attaque', fmt: 'r7', title: 'À 7 : faire courir la défense', goal: 'Utiliser toute la largeur et le surnombre pour marquer.', ex: [
        ['attaque', 'Surnombre à 3 contre 2 sur la largeur', 12, 'Trois attaquants contre deux défenseurs sur toute la largeur : fixer, passer, finir.', 'Fixer son vis-à-vis|Passer au dernier moment|Finir en accélérant', 'Plots, ballons', ''],
        ['soutien', 'Garder le ballon après le contact', 12, 'Le porteur va au contact, deux soutiens arrivent vite et relancent.', 'Rester debout|Soutien immédiat|Ballon relancé vite', 'Boucliers, ballons', ''],
        ['jeu', 'Match à 7 : 7 minutes par mi-temps', 20, 'Match au format du rugby à 7.', 'Patience|Largeur|Repli', 'Chasubles', '']] },
      { sys: 'Rugby à 7 : défense', fmt: 'r7', title: 'À 7 : défendre la largeur', goal: 'Défendre à 7 sur toute la largeur sans laisser d\'espace.', ex: [
        ['plaquage', 'Défense en glissée à 4 contre 5', 12, 'Quatre défenseurs contre cinq attaquants : la défense glisse vers la touche.', 'Monter ensemble|L\'extérieur ferme|Plaquer le porteur', 'Plots, ballons', ''],
        ['plaquage', 'Plaquage en 1 contre 1 dans un couloir large', 12, 'Couloir de 15 m : un défenseur contre un attaquant lancé.', 'Réduire l\'espace|Petits pas|Plaquer bas', 'Plots, boucliers', ''],
        ['jeu', 'Match à 7 : un plaquage réussi = 1 point', 15, 'Match : chaque plaquage qui arrête l\'attaque rapporte 1 point à la défense.', 'Défense agressive|Communication', 'Chasubles', '']] },
      { sys: 'École de rugby : avancer', fmt: 'r10', title: 'Avancer ensemble avec le ballon', goal: 'Porter le ballon vers l\'avant, passer en arrière, soutenir le porteur.', ex: [
        ['passe', 'Passes en arrière en avançant', 10, 'Par 3 sur 20 m : on avance et on passe toujours vers l\'arrière.', 'Passer en arrière|Soutien derrière le porteur|Courir droit', 'Ballons, plots', ''],
        ['soutien', 'Le porteur et ses soutiens', 12, 'Le porteur avance, deux soutiens le suivent de près et reçoivent quand il est touché.', 'Rester proche|Appeler le ballon|Se placer derrière', 'Ballons', ''],
        ['jeu', 'Jeu au toucher à 5 contre 5', 15, 'Petit terrain : au toucher, passe obligatoire.', 'Avancer|Passer en arrière|Soutenir', 'Chasubles', '']] },
      { sys: 'École de rugby : plaquer', fmt: 'r10', title: 'Plaquer en sécurité', goal: 'Apprendre le plaquage pas à pas, sans risque.', ex: [
        ['plaquage', 'Plaquage à genoux', 10, 'Par 2 à genoux : joue contre la fesse, bras autour des cuisses, on accompagne au sol.', 'Tête sur le côté|Serrer les bras|Accompagner', 'Tapis', ''],
        ['plaquage', 'Plaquage accroupi sur porteur qui marche', 12, 'Le porteur marche, le plaqueur accroupi le plaque aux cuisses.', 'Tête sur le côté|Épaule dans les cuisses|Serrer', 'Tapis, ballons', ''],
        ['jeu', 'Match à thème : plaquage à deux mains au début', 15, 'Petit match où le plaquage est remplacé par une ceinture à deux mains.', 'Viser la taille|Serrer|Se relever vite', 'Chasubles', '']] },
      { sys: 'Jeu groupé (après ruck)', fmt: 'r15', title: 'Avancer par le jeu groupé', goal: 'Enchaîner les rucks rapides et avancer temps de jeu après temps de jeu.', ex: [
        ['soutien', 'Ruck rapide à deux arrivées', 12, 'Le porteur va au sol, deux soutiens nettoient, le demi sort le ballon.', 'Arriver bas|Pousser au-delà du ballon|Ballon dégagé vite', 'Boucliers, ballons', ''],
        ['contact', 'Porteur qui reste debout', 12, 'Le porteur va au contact d\'un bouclier, reste debout et présente le ballon.', 'Appuis larges|Épaule basse|Ballon loin', 'Boucliers, ballons', ''],
        ['jeu', 'Match : 5 temps de jeu avant de jouer au large', 20, 'Match : l\'attaque doit enchaîner 5 rucks avant de passer au large.', 'Patience|Soutien|Placement des avants', 'Chasubles', '']] },
      { sys: 'Défense glissée', fmt: 'r15', title: 'Défense glissée vers la touche', goal: 'Monter ensemble puis glisser pour pousser l\'attaque vers la touche.', ex: [
        ['plaquage', 'Glisser à 4 contre 5', 12, 'Quatre défenseurs contre cinq attaquants : la ligne glisse vers l\'extérieur.', 'Monter ensemble|Glisser dès la passe|L\'extérieur ferme', 'Plots, ballons', ''],
        ['plaquage', 'Plaquage puis relevé', 12, 'Le défenseur plaque un porteur, se relève et revient dans la ligne.', 'Plaquer bas|Se relever vite|Se replacer', 'Boucliers, ballons', ''],
        ['jeu', 'Match : la défense marque si elle pousse en touche', 20, 'Match : un porteur poussé en touche donne 2 points à la défense.', 'Organisation|Communication', 'Chasubles', '']] },
      { sys: 'Contre-attaque', fmt: 'r15', title: 'Contre-attaquer sur un coup de pied', goal: 'Réceptionner le coup de pied adverse et relancer avant que la défense se place.', ex: [
        ['pied', 'Réception de chandelle', 10, 'Le receveur annonce, réceptionne, protège le ballon.', 'Annoncer fort|Bras en corbeille|Se retourner', 'Ballons', ''],
        ['attaque', 'Relance à 3 après réception', 12, 'Le receveur et deux partenaires relancent face à deux poursuivants.', 'Se regrouper vite|Attaquer l\'espace|Passer avant le contact', 'Ballons, plots', ''],
        ['jeu', 'Match : chaque coup de pied doit être relancé', 20, 'Match : sur coup de pied adverse, interdiction de retaper au pied.', 'Lire les espaces|Soutien', 'Chasubles', '']] },
      { sys: 'Lancement de jeu', fmt: 'r15', title: 'Lancer le jeu en première main', goal: 'Marquer ou avancer dès la première passe après une mêlée ou une touche.', ex: [
        ['attaque', 'Croisée et passe décalée', 12, 'Trois attaquants : croisée, puis passe à l\'extérieur.', 'Courses qui se croisent près|Passe courte|Lire le défenseur', 'Plots, ballons', ''],
        ['attaque', 'Jeu à partir de la mêlée', 15, 'Après la mêlée, le demi passe à l\'ouvreur, les trois-quarts lancent une combinaison annoncée.', 'Annonce avant la mêlée|Alignement profond|Tenir sa course', 'Ballons', ''],
        ['jeu', 'Match à thème : lancement imposé', 20, 'Match : à chaque mêlée, l\'attaque joue la combinaison du jour.', 'Précision|Soutien', 'Chasubles', '']] },
    ],
    volley: [
      { sys: '4 contre 4 : passeur au centre', fmt: 'v4', title: 'Jouer à 4 : passeur au centre', goal: 'Un passeur au centre, deux attaquants, un défenseur arrière : construire chaque point.', ex: [
        ['technique', 'Touche haute en déplacement', 10, 'Le passeur se déplace sous chaque réception et passe vers l\'aile.', 'Arriver sous le ballon|Mains en coupe|Pousser avec les jambes', 'Ballons', ''],
        ['attaque', 'Attaque des ailes à 4', 12, 'Réception, passe au centre, attaque en zone 4 ou 2.', 'Élan en 3 temps|Frapper devant soi|Viser l\'espace', 'Ballons, filet', ''],
        ['jeu', 'Match à 4 contre 4 avec 3 touches', 20, 'Match : trois touches obligatoires.', 'Construire|Se parler', 'Ballons, filet', '']] },
      { sys: '4 contre 4 : défense', fmt: 'v4', title: 'Défendre à 4', goal: 'Se partager le terrain à 4 et couvrir l\'attaquant.', ex: [
        ['defense', 'Défense à 3 sur attaque du coach', 12, 'Le coach attaque, trois défenseurs remontent le ballon vers le passeur.', 'Position basse|Bras sous le ballon|Ballon haut au centre', 'Ballons, chaise', ''],
        ['defense', 'Couverture de l\'attaquant', 12, 'Les trois autres entourent l\'attaquant pour reprendre un ballon contré.', 'Se rapprocher bas|Bras prêts|Relancer haut', 'Ballons, filet', ''],
        ['jeu', 'Match à 4 : défense = 1 point', 15, 'Match : une défense réussie sur attaque rapporte 1 point.', 'Engagement|Couverture', 'Ballons, filet', '']] },
      { sys: 'Service tactique', fmt: 'v6', title: 'Servir pour gêner l\'adversaire', goal: 'Viser le réceptionneur faible ou la zone du passeur.', ex: [
        ['service', 'Service tennis flottant', 12, 'Service flottant vers une zone annoncée.', 'Lancer devant l\'épaule|Frappe sèche au centre|Ne pas accompagner', 'Ballons, filet', ''],
        ['service', 'Service sur le réceptionneur désigné', 12, 'Le coach désigne un réceptionneur, les serveurs le visent.', 'Regarder la cible avant|Service sûr|Varier court et long', 'Ballons, filet', ''],
        ['jeu', 'Match : as = 2 points', 20, 'Match : un service gagnant compte double, un service raté donne 2 points à l\'autre.', 'Prendre un risque mesuré|Routine', 'Ballons, filet', '']] },
      { sys: 'Attaque croisée', fmt: 'v6', title: 'L\'attaque croisée', goal: 'Deux attaquants qui se croisent pour tromper le contre.', ex: [
        ['attaque', 'Attaque en zone 2', 12, 'Le passeur passe en arrière vers la zone 2.', 'Élan en 3 temps|Frapper devant|Viser diagonale ou ligne', 'Ballons, filet', ''],
        ['attaque', 'Croisé entre le central et l\'ailier', 15, 'Le central fait un appel court, l\'ailier croise derrière lui : le passeur choisit.', 'Appel du central crédible|Timing de l\'ailier|Passe rapide', 'Ballons, filet', ''],
        ['jeu', 'Match : attaque croisée = 2 points', 20, 'Match : un point marqué sur attaque croisée compte double.', 'Communication passeur-attaquants', 'Ballons, filet', '']] },
      { sys: 'Contre à trois', fmt: 'v6', title: 'Fermer le filet à trois', goal: 'Trois contreurs qui se déplacent ensemble vers l\'attaquant servi.', ex: [
        ['contre', 'Contre seul : lire le passeur', 12, 'Le contreur lit le passeur puis l\'attaquant et saute au bon moment.', 'Passeur puis attaquant|Sauter juste après|Mains vers l\'intérieur', 'Ballons, filet', ''],
        ['contre', 'Déplacement du contre à trois', 12, 'Trois contreurs se déplacent ensemble vers l\'aile appelée par le coach.', 'Pas chassés puis croisé|Se coller l\'un à l\'autre|Mains fermées', 'Filet', ''],
        ['jeu', 'Match : contre gagnant = 2 points', 20, 'Match : un point marqué au contre compte double.', 'Organisation|Couverture derrière', 'Ballons, filet', '']] },
      { sys: 'Défense en 6 avancé', fmt: 'v6', title: 'Défendre avec le 6 avancé', goal: 'Le joueur de la zone 6 monte derrière le contre pour récupérer les balles placées.', ex: [
        ['defense', 'Défense sur balles placées', 12, 'Le coach place des ballons derrière le contre, le 6 avancé les récupère.', 'Monter derrière le contre|Rester bas|Remonter haut', 'Ballons, filet', ''],
        ['defense', 'Défense en 6 avancé sur attaque', 15, 'Attaque du coach en zones 4 et 2 : les arrières se placent avec le 6 avancé.', 'Chacun sa zone|Bras prêts|Se parler', 'Ballons, filet', ''],
        ['jeu', 'Match avec 6 avancé', 20, 'Match normal : les équipes défendent en 6 avancé.', 'Placement|Communication', 'Ballons, filet', '']] },
      { sys: 'Transition défense-attaque', fmt: 'v6', title: 'Contre-attaquer après une défense', goal: 'Défendre, se replacer et attaquer vite derrière.', ex: [
        ['defense', 'Défense et relance en manchette', 12, 'Le coach attaque, le défenseur remonte haut vers le centre.', 'Position basse|Bras sous le ballon|Ballon haut', 'Ballons, chaise', ''],
        ['attaque', 'Défense puis attaque enchaînée', 15, 'Après chaque défense, le passeur sert un attaquant qui s\'est replacé pour l\'élan.', 'Se replacer vite|Passe haute|Attaque décidée', 'Ballons, filet', ''],
        ['jeu', 'Match : point en transition = 2 points', 20, 'Match : un point marqué juste après une défense compte double.', 'Enchaîner|Se parler', 'Ballons, filet', '']] },
      { sys: 'Jeu du libéro', fmt: 'v6', title: 'Le libéro au cœur de la réception', goal: 'Le libéro prend le plus de réceptions et organise la défense.', ex: [
        ['reception', 'Réception à 3 avec libéro au centre', 15, 'Le libéro au centre prend toutes les balles qu\'il peut, les ailes prennent le reste.', 'Annoncer tôt|Être arrêté avant la frappe|Viser le passeur', 'Ballons, filet', ''],
        ['defense', 'Le libéro dirige la défense', 12, 'Sur attaques du coach, le libéro annonce les placements.', 'Parler fort|Position basse|Relancer haut', 'Ballons, filet', ''],
        ['jeu', 'Match avec libéro', 20, 'Match normal avec un libéro dans chaque équipe.', 'Remplacements du libéro|Réception', 'Ballons, filet', '']] },
    ],
  };
  if (X) Object.keys(EX).forEach(k => { if (!X[k]) return; const has = new Set(X[k].base.map(b => b[1])); EX[k].forEach(b => { if (!has.has(b[1])) X[k].base.push(b); }); });
  if (SS) Object.keys(SES).forEach(k => { SS[k] = SS[k] || []; SES[k].forEach(s => { if (!SS[k].some(x => x.sys === s.sys && x.title === s.title)) SS[k].push(s); }); });
})();
